# Generated by Django 5.2.8 on 2025-11-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, upload_to='applications/', verbose_name='Фото помещения или план'),
        ),
    ]
