# Generated by Django 5.2.8 on 2025-11-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_application_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(upload_to='applications/', verbose_name='Фото помещения или план'),
        ),
    ]
